name: Commons
main: com.caved_in.commons.Commons
version: ${project.version}
description: An all-in-one plugin to provide features to both server owners, and developers.
author: Brandon Curtis (TheGamersCave)
softdepend: [TagAPI, ProtocolLib]
commands:
   buypremium:
      description: Used to add premium (Console only)
      usage: /<command> <PlayerName>
   removepremium:
      description: Used to remove premium (Console only)
      usage: /<command> <PlayerName>
   msg:
      usage: /msg <player> <message>
      aliases: [m, t, tell, whisper]
   ci:
      usage: /<command> [player]
      aliases: [clearinventory, clearinv]
   tphere:
      usage: /<command> <player>
      aliases: [bring]
   tpa:
      usage: /<command> <player>
   tpahere:
      usage: /<command> <player>
   tpaccept:
      usage: /<command>
   tpdeny:
      usage: /<command>
   tp:
      usage: /<command> <player>
      aliases: [teleport]
   tpo:
      usage: /<command> <player> <targetPlayer>
      aliases: [tpother,teleportother]
   fly:
      usage: /fly
   fw:
      usage: /fw
   hat:
      usage: /msg <player>
   gm:
      usage: /gm [Mode]
   god:
      usage: /god
   maintenance:
      usage: /maintenance [on/off/toggle]
   silence:
      usage: /silence
   unsilence:
      usage: /unsilence
   nick:
      usage: /nick help
   nicklist:
      usage: /nicklist
   friends:
      usage: /friends <SubCommand>
   r:
      usage: /<command> <Message>
   skull:
      usage: /<command> <Name>
   setspawn:
      usage: /setspawn
   xp:
      usage: /<command>
   more:
      usage: /<command>
   addcurrency:
      usage: /<command> <Player> <Amount>
   heal:
      usage: /<command>
   i:
      usage: /<command> <Item> [Amount]
      aliases: [item]
   speed:
      usage: /<command> <speed>
   time:
      usage: /<command> <time>
   day:
      usage: /<command>
   night:
      usage: /<command>
   enchant:
      usage: /<command>
   repair:
      usage: /<command>
   recipe:
      usage: /<command> [item name or id]
   feed:
      usage: /<command> [player]
   spawnmob:
      usage: /<command> <Mob> [Amount]
   workbench:
      usage: /<command> [Player]
      aliases: [wb, wbench]
   tpall:
      usage: /<command>
   spawn:
      usage: /<command>
   tppos:
      usage: /<command> <x> <y> <z>
   warp:
      usage: /<command> <name>
   warps:
      usage: /<command> [page]
   setwarp:
      usage: /<command> <name>
   back:
      usage: /<command>
   potion:
      usage: /<command> <type> [Level]
   debug:
      usage: /<command>
   slay:
      usage: /<command> <radius> [kill players (yes/no)]
   armor:
      usage: /<command> <type>
   rename:
      usage: /<command> <item name>
   blocktext:
      usage: /<command> <item-data> <text>...
   id:
      usage: /<command> [item name]
   set:
      usage: /<command> [name]
   clean:
      usage: /<command> <mobs/items/fluids>
permissions:
   commons.admin.*:
      description: Gives access to all the administrative commands and tasks within tunnels
      default: op
      children:
        commons.admin: true
   commons.addcurrency:
      description: Allows you to use the addcurrency command
      default: op
   commons.back:
      description: Allows you to use the back command
      default: op
   commons.ban:
      description: Allows you to use the ban command
      default: op
   commons.buypremium:
      description: Allows you to use the buypremium command
      default: op
   commons.clearinventory:
      description: Allows you to use the clearinventory command
      default: op
   commons.day:
      description: Allows you to use the day command
      default: op
   commons.debug:
      description: Allows you to view 'debug' information when performing events, actions and tasks.
      default: op
   commons.enchant:
      description: Allows you to use the enchant command
      default: op
   commons.feed:
      description: Allows you to use the feed command
      default: op
   commons.fireworks:
      description: Allows you to use the fireworks commands
      default: op
   commons.fly:
      description: Allows you to use the fly command, and be in fly mode
      default: op
   commons.friends:
      description: Allows you to use the friends list feature
      default: true
      default: op
   commons.gamemode:
      description: Allows you to change your gamemode
      default: op
   commons.hat:
      description: I MUST SAY SIR, YOUR TOPHAT LOOKS ABSOLUTELY SPIFFING!
      default: op